<?php
/**
 * Error500ObjTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  TipoCrawler\Api
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Tipo API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 2.4.0-SNAPSHOT
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace TipoCrawler\Api;

/**
 * Error500ObjTest Class Doc Comment
 *
 * @category    Class
 * @description Error500Obj
 * @package     TipoCrawler\Api
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class Error500ObjTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "Error500Obj"
     */
    public function testError500Obj()
    {
    }

    /**
     * Test attribute "prop1"
     */
    public function testPropertyProp1()
    {
    }

    /**
     * Test attribute "prop2"
     */
    public function testPropertyProp2()
    {
    }
}
