<?php
/**
 * ResultItemTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  TipoCrawler\Api
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Tipo API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 2.4.0-SNAPSHOT
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace TipoCrawler\Api;

/**
 * ResultItemTest Class Doc Comment
 *
 * @category    Class
 * @description ResultItem
 * @package     TipoCrawler\Api
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class ResultItemTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "ResultItem"
     */
    public function testResultItem()
    {
    }

    /**
     * Test attribute "trademark_name"
     */
    public function testPropertyTrademarkName()
    {
    }

    /**
     * Test attribute "application_number"
     */
    public function testPropertyApplicationNumber()
    {
    }

    /**
     * Test attribute "registeration_number"
     */
    public function testPropertyRegisterationNumber()
    {
    }

    /**
     * Test attribute "national_classes"
     */
    public function testPropertyNationalClasses()
    {
    }

    /**
     * Test attribute "name_of_applicant"
     */
    public function testPropertyNameOfApplicant()
    {
    }

    /**
     * Test attribute "name_of_applicant_in_english"
     */
    public function testPropertyNameOfApplicantInEnglish()
    {
    }

    /**
     * Test attribute "item_type"
     */
    public function testPropertyItemType()
    {
    }

    /**
     * Test attribute "case_number"
     */
    public function testPropertyCaseNumber()
    {
    }

    /**
     * Test attribute "case_type"
     */
    public function testPropertyCaseType()
    {
    }

    /**
     * Test attribute "application_number_enc"
     */
    public function testPropertyApplicationNumberEnc()
    {
    }
}
