<?php
/**
 * SearchApiTest
 * PHP version 5
 *
 * @category Class
 * @package  TipoCrawler\Api
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Tipo API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 2.4.0-SNAPSHOT
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the endpoint.
 */

namespace TipoCrawler\Api;

use \TipoCrawler\Api\Configuration;
use \TipoCrawler\Api\ApiException;
use \TipoCrawler\Api\ObjectSerializer;

/**
 * SearchApiTest Class Doc Comment
 *
 * @category Class
 * @package  TipoCrawler\Api
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class SearchApiTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test case for apiSearchDetailsPost
     *
     * .
     *
     */
    public function testApiSearchDetailsPost()
    {
    }

    /**
     * Test case for apiSearchError500Post
     *
     * .
     *
     */
    public function testApiSearchError500Post()
    {
    }

    /**
     * Test case for apiSearchPost
     *
     * .
     *
     */
    public function testApiSearchPost()
    {
    }
}
